### ISSUE TITLE
Fails to build with perl 5.43+5.44

### ISSUE THREAD

**Issue by eserte** [avar/re-engine-pcre#7]
The distribution worked fine to build with perl 5.29 .. 5.42 when applying the patches
  - SREZIC/patches/re-engine-PCRE-0.17-RT108386.patch
  - SREZIC/patches/re-engine-PCRE-0.17-RT129403.patch
However, since 5.43.5 there's a new compilation error:
```
cc -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"0.17\" -DXS_VERSION=\"0.17\" -fPIC "-I/opt/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux/CORE"   PCRE.c
In file included from PCRE.xs:7:0:
PCRE.h:22:5: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     PCRE_comp,
     ^~~~~~~~~
PCRE.h:22:5: note: (near initialization for ‘pcre_engine.comp’)
PCRE.h:23:5: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     PCRE_exec,
     ^~~~~~~~~
PCRE.h:23:5: note: (near initialization for ‘pcre_engine.exec’)
PCRE.h:24:5: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     PCRE_intuit,
     ^~~~~~~~~~~
PCRE.h:24:5: note: (near initialization for ‘pcre_engine.intuit’)
PCRE.h:27:5: error: ‘Perl_reg_numbered_buff_fetch’ undeclared here (not in a function)
     Perl_reg_numbered_buff_fetch,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
PCRE.h:28:5: error: ‘Perl_reg_numbered_buff_store’ undeclared here (not in a function)
     Perl_reg_numbered_buff_store,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
PCRE.h:29:5: error: ‘Perl_reg_numbered_buff_length’ undeclared here (not in a function)
     Perl_reg_numbered_buff_length,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PCRE.h:30:5: error: ‘Perl_reg_named_buff’ undeclared here (not in a function)
     Perl_reg_named_buff,
     ^~~~~~~~~~~~~~~~~~~
PCRE.h:31:5: error: ‘Perl_reg_named_buff_iter’ undeclared here (not in a function)
     Perl_reg_named_buff_iter,
     ^~~~~~~~~~~~~~~~~~~~~~~~
Makefile:344: recipe for target 'PCRE.o' failed
make: *** [PCRE.o] Error 1
```
